[package]
name = "console_engine"
description = "A simple terminal framework to draw things and manage user input"
version = "1.4.1"
authors = ["Vincent Foulon <sup.vfoulon@gmail.com>"]
repository = "https://github.com/VincentFoulon80/console_engine"
readme = "README.md"
keywords = ["terminal","tui", "input"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18"

[dev-dependencies]
rand = "0.7"
